### ISSUE TITLE
Ability to resize banner

### ISSUE THREAD

**Issue by saintnicster** [XjSv/environment-marker#10]
I'd like to see the ability to have different size options available for the banner, to help it stand out more.

**Comment by XjSv** [comment]
Sounds like it would be a good feature. I will add it to the list.

**Comment by XjSv** [comment]
Release [v2.2](https://github.com/XjSv/environment-marker/releases/tag/v2.2) fixes this issue.

I have added 5 different sizes:
- Extra Small
- Small
- Normal
- Large
- Extra Large

Let me know if this suffices, if not please open another issue.
