### ISSUE TITLE
Choose file field does not seem interactive

### ISSUE THREAD

**Issue by miellaby** [XjSv/environment-marker#103]
There is no file selector entry related with the import button and when clicking the button it says there is no file selected.

**To Reproduce**
1. Go to options
2. Click on import

**Expected behavior**
By looking at the code, I noticed there was a hidden file input. By displaying it, I was able to make the feature works.

**Information (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
- extension version 2.5.2

**Comment by XjSv** [comment]
I believe this might just be a documentation issue. If you click the "Choose file" text you should be prompted to select a file.

<img width="622" alt="choose-file" src="https://user-images.githubusercontent.com/107681/135647648-aa3e3619-3839-4ca6-b42d-5d6b6edb3073.png">

**Comment by miellaby** [comment]
Thanks for the explanation. I suggest adding the "form-control d-inline" css class so that it appears like a form entry.

**Comment by XjSv** [comment]
> 
> 
> Thanks for the explanation. I suggest adding the "form-control d-inline" css class so that it appears like a form entry.

That is actually a great suggestion, I am including it in the next release. Thanks!
