### ISSUE TITLE
Add support for wrapping logic

### ISSUE THREAD

**Issue by Splaxi** [XjSv/environment-marker#20]
You should consider adding support for wrapping / breaking the text into multiple lines or simply support "enter" as character and that way have it break the text.

When using to long text, it doesn't show all to well.

![image](https://user-images.githubusercontent.com/8750181/108470845-d9334000-728a-11eb-89e4-b95d698c42ad.png)

![image](https://user-images.githubusercontent.com/8750181/108470605-82c60180-728a-11eb-88b3-3c0d5ce8cdfb.png)

**Comment by XjSv** [comment]
I definitely do not like the way I am currently handling long text. Currently anything over 30 characters gets truncated and ellipses are added at the end, which is not an ideal solution. The assumption was that in the label field people will add short labels or tags to identify environments such as: Dev, QA, UAT, Prod, etc.

I don't know if wrapping the text would be a good solution. Some things to consider would be:

- How would wrapping text work with different ribbon sizes such as Extra Small or Small? The smaller ribbons do not have much space to allow for wrapping text.
- Considering https://github.com/XjSv/environment-marker/issues/19, how would large font sizes work with Extra Small or Small ribbon sizes? There must be some sort of max font size that is different per ribbon size. For example we cannot have a font size of 64px for a Extra Small ribbon.

**Comment by Splaxi** [comment]
Initially people would only add single short words, but being a consultant or work in a VERY large company, you need system name like:

SystemA-DEV
SystemA-SIT

Having the possibility to differentiate environments while adding enough text to give context, is a killer feature.

I don't know how to solve it, but an option could be to support 4 text per url. That would allow the user to split text and that way give context. 

Or simply add a top or bottom text bar, that spans from left to right, would allow limitless text support.
