### ISSUE TITLE
Description could be stated in a simpler way

### ISSUE THREAD

**Issue by XjSv** [XjSv/environment-marker#5]
... maybe a little change in the description would be clever : "Adds 
a color marker (ribbon) to the top left of the page depending if the 
URL contains a given string (e.g. 'http://dev-', 'http://prod-'). It 
uses JavaScript's indexOf to determine if the string is found"

-> i do not understant the part "if the URL contains a given string 
(e.g. 'http://dev-', 'http://prod-'" ... maybe we should delete this 
and just write :
Adds a color marker (ribbon) to the page depending on the URL ?

_Originally posted by @loguilhem in https://github.com/XjSv/environment-marker/pull/4#issuecomment-620618170_

**Comment by XjSv** [comment]
I agree, it is a little confusing for some people that might not know or not care what that means and we should change it to something different. Maybe even exactly what @loguilhem said. The only thing is that the URL parameter can be part of a string such as just 'dev'. Which will match on any URL containing the string 'dev' such as:

- ht<span>tps://</span>www.**dev**.to
- ht<span>tps://</span>www.**dev**.example.com
- ht<span>tps://</span>www.example.com/**dev**

And I think if we say "depending on the URL", at first people might think that it's necessary to put the entire URL or domain in. 

**This is my first suggestion:**
A Firefox WebExtension that adds a color marker (ribbon) to the page depending if the URL contains a given string.

@loguilhem What do you think?

**Comment by loguilhem** [comment]
i am ok with the description that you propose. Let me know when you make the build so i can install it from Firefox.

Also, i have an idea of a new feature : the possibility to import/export a list of url (with the colors, labels...) so a new coworker could set up the extension in a flash.

**Comment by XjSv** [comment]
I have already updated the addon in the addons.mozilla.org with [v1.8](https://github.com/XjSv/environment-marker/releases/tag/v1.8). You should already have the latest version if you have auto update enabled. Also I created issue https://github.com/XjSv/environment-marker/issues/6 to track the Import/Export feature.

**Comment by XjSv** [comment]
I have updated the description in addons.mozilla.org. I also updated the project and the readme.md. When I package up the next release we it will be included.
