### ISSUE TITLE
Adding multiple URLs as one item on the markers list (having the same color)

### ISSUE THREAD

**Issue by onlyhuman** [XjSv/environment-marker#7]
Considering that the user has access multiple e.g. PROD environments it makes sense to add the new URL as e.g. a list separated by e.g. comma. Instead of defining new rows/colors to the markers list. Or it is already possible? I could not make it to work.

**Comment by XjSv** [comment]
No unfortunately this is not an option yet. Essentially what you are asking is to make it possible to add multiple URL's and group them under one color at the same time. It's possible to get the end result of what you are asking in a different way.

For example if you have multiple production URL's such as:
- https://prod.example1.com
- https://prod.example2.com
- https://prod.example3.com

You don't have to create a entry for each. What you could do instead is enter just `prod.` or `https://prod.` as you URL fragment. 
This is why the input field is labeled as "URL fragment" in the placeholder. It's not necessary to enter the full URL, only a portion of it will work too.

This ultimately boils down to documentation I think. Maybe it's not clear as to how you can use it.
