### ISSUE TITLE
Add Option to Enable or Disable the Tab Counter

### ISSUE THREAD

**Issue by miellaby** [XjSv/environment-marker#78]
I love your plugin. But the tab count pill within the plugin icon is annoying.

I suggest to remove it.

Or to add an option to mask it

Or to make this counter counts only marked tabs (with a matching  rule) and automatically hide it when equals 0.

**Comment by XjSv** [comment]
The new release should be pushed out from all the browsers soon. @miellaby see https://github.com/XjSv/environment-marker/wiki/Settings#tab-counter for more information on the Tab Counter setting.
